### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by robinwhittleton** [ncwmail/edgar-wallace_the-council-of-justice#1]
general
- typogrify and semanticate make a few valid changes

content.opf
- Could the longdesc be expanded with setting the book in context? How was it received? Where was it placed in the author’s career? etc.

chapter-1
- the second `<blockquote>` should be an `<ol>` instead - we can remove the custom CSS afterwards

chapter-3
- the `z3998:verse` semantics should probably be `z3998:song`; would need to add styling in local.css as well.

**Comment by ncwmail** [comment]
Many thanks. Agree with all of your comments and corrections made

**Comment by robinwhittleton** [comment]
For the list, you’ll to add list items and remove the numbering (it’ll be inserted automatically). So:

```
<ol>
	<li>
		<p>General Maloff shot dead by an unknown woman in his private room at the Police Bureau, Moscow.</p>
	</li>
	<li>
		<p>Prince Hazallarkoff shot dead by an unknown woman in the streets of Petrograd.</p>
	</li>
	<li>
		<p>Colonel Kaverdavskov killed by a bomb thrown by a woman who made her escape.</p>
	</li>
</ol>
```

**Comment by robinwhittleton** [comment]
For the song styling, we’d want to duplicate the verse styling. We can do that with selectors that target both. So:

```
[epub|type~="z3998:song"] p,
[epub|type~="z3998:verse"] p{
	text-align: initial;
	text-indent: 0;
}

[epub|type~="z3998:song"] p > span,
[epub|type~="z3998:verse"] p > span{
	display: block;
	padding-left: 1em;
	text-indent: -1em;
}

[epub|type~="z3998:song"] p > span + br,
[epub|type~="z3998:verse"] p > span + br{
	display: none;
}
```
